name: License Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  js-license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Run JavaScript license check
        run: node scripts/check_js_licenses.js
